"""
Generate the macOS and Linux spec files from the Windows spec file.

The Windows spec file (spec-file-win-64.txt) is the reference environment.
This script reads the versions of the key packages from it, asks conda to
solve an environment with those same versions for each other platform, and
writes the result to spec-file-<platform>.txt.

Run from the repository root, with conda available on the command line:
    python generate_spec_files.py                  # all platforms
    python generate_spec_files.py osx-arm64        # specific platform
"""

import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REFERENCE_SPEC = ROOT / "spec-file-win-64.txt"
ENVIRONMENT_FILE = ROOT / "environment.yml"
PLATFORMS = ["osx-arm64", "osx-64", "linux-64"]

# conda only detects the system library versions of the computer it runs on,
# so give it the minimum versions to assume for other platforms
VIRTUAL_PACKAGE_OVERRIDES = {
    "linux": {"CONDA_OVERRIDE_GLIBC": "2.17"},
    "osx": {"CONDA_OVERRIDE_OSX": "11.0"},
}

# packages that are not listed in environment.yml but whose versions should
# still match the Windows environment
# e.g. pythonocc-core needs vtk on Windows and macOS but not on Linux.
EXTRA_PINNED = ["numpy", "vtk", "occt"]

def read_environment_packages():
    """Return the package names under dependencies in environment.yml"""
    names = []
    in_dependencies = False
    for line in ENVIRONMENT_FILE.read_text().splitlines():
        if line.startswith("dependencies:"):
            in_dependencies = True
        elif in_dependencies and line.strip().startswith("- "):
            names.append(re.split(r"[=<>! ]", line.strip()[2:])[0])
        elif in_dependencies and line.strip():
            in_dependencies = False
    return names


def read_reference_versions():
    """Return {package name: version} from the Windows spec file"""
    versions = {}
    for line in REFERENCE_SPEC.read_text().splitlines():
        if not line.startswith("http"):
            continue
        filename = line.rsplit("/", 1)[1]
        filename = re.sub(r"\.(conda|tar\.bz2)$", "", filename)
        name, version, _build = filename.rsplit("-", 2)
        versions[name] = version
    return versions


def solve(platform, specs, constraints):
    """Solve the environment for a platform and return the package URLs"""
    command = [
        "conda", "create", "--name", "_spec_file_solve", "--dry-run", "--json",
        "--platform", platform,
        "--override-channels", "--channel", "conda-forge",
        *specs,
    ]
    environment = dict(os.environ)
    environment["CONDA_PINNED_PACKAGES"] = "&".join(constraints)
    target_os = platform.split("-")[0]
    current_os = {"darwin": "osx", "win32": "win"}.get(sys.platform, sys.platform)
    if target_os != current_os:
        environment.update(VIRTUAL_PACKAGE_OVERRIDES.get(target_os, {}))
    result = subprocess.run(command, capture_output=True, text=True,
                            env=environment, shell=sys.platform == "win32")
    data = json.loads(result.stdout)
    if not data.get("success"):
        raise RuntimeError(data.get("message", result.stderr))
    urls = []
    for package in data["actions"]["LINK"]:
        url = f"{package['base_url']}/{package['platform']}/{package['dist_name']}"
        urls.append(add_extension(url))
    return urls


def add_extension(url):
    for extension in (".conda", ".tar.bz2"):
        request = urllib.request.Request(url + extension, method="HEAD")
        try:
            urllib.request.urlopen(request, timeout=30)
            return url + extension
        except urllib.error.HTTPError:
            pass
    raise RuntimeError(f"no package file found for {url}")


def write_spec_file(platform, urls):
    path = ROOT / f"spec-file-{platform}.txt"
    header = [
        "# This file may be used to create an environment using:",
        "# $ conda create --name <env> --file <this file>",
        f"# platform: {platform}",
        "# generated by generate_spec_files.py from spec-file-win-64.txt",
        "@EXPLICIT",
    ]
    path.write_text("\n".join(header + urls) + "\n")
    print(f"wrote {path.name} ({len(urls)} packages)")


def main():
    platforms = sys.argv[1:] or PLATFORMS
    versions = read_reference_versions()
    specs = []
    for name in read_environment_packages():
        if name == "pip":
            specs.append(name)
        elif name in versions:
            specs.append(f"{name}={versions[name]}")
        else:
            sys.exit(f"{name} is in environment.yml but not in {REFERENCE_SPEC.name}")
    constraints = [f"{name}={versions[name]}" for name in EXTRA_PINNED]
    print("required:", " ".join(specs))
    print("constrained:", " ".join(constraints))
    for platform in platforms:
        print(f"solving {platform}...", flush=True)
        write_spec_file(platform, solve(platform, specs, constraints))


if __name__ == "__main__":
    main()
