"""
Generate the macOS and Linux spec files from the Windows spec file.

The Windows spec file (spec-file-win-64.txt) is the reference environment.
This script reads the versions of the key packages from it, asks conda to
solve an environment with those same versions for each other platform, and
writes the result to spec-file-<platform>.txt.

Run from the repository root, with conda available on the command line:
    python generate_spec_files.py                  # all platforms
    python generate_spec_files.py osx-arm64        # specific platform
    python generate_spec_files.py --check          # check for stale files
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REFERENCE_SPEC = ROOT / "spec-file-win-64.txt"
ENVIRONMENT_FILE = ROOT / "environment.yml"
PLATFORMS = ["osx-arm64", "osx-64", "linux-64"]

# conda only detects the system library versions of the computer it runs on,
# so give it the minimum versions to assume for other platforms
VIRTUAL_PACKAGE_OVERRIDES = {
    "linux": {"CONDA_OVERRIDE_GLIBC": "2.17"},
    "osx": {"CONDA_OVERRIDE_OSX": "11.0"},
}

# packages that are not listed in environment.yml but whose versions should
# still match the Windows environment
# e.g. pythonocc-core needs vtk on Windows and macOS but not on Linux.
EXTRA_PINNED = ["numpy", "vtk", "occt"]

def read_environment_packages():
    """Return the package names under dependencies in environment.yml"""
    names = []
    in_dependencies = False
    for line in ENVIRONMENT_FILE.read_text().splitlines():
        if line.startswith("dependencies:"):
            in_dependencies = True
        elif in_dependencies and line.strip().startswith("- "):
            names.append(re.split(r"[=<>! ]", line.strip()[2:])[0])
        elif in_dependencies and line.strip():
            in_dependencies = False
    return names


def read_spec_versions(path):
    """Return {package name: version} from a spec file"""
    versions = {}
    for line in path.read_text().splitlines():
        if not line.startswith("http"):
            continue
        filename = line.rsplit("/", 1)[1]
        filename = re.sub(r"\.(conda|tar\.bz2)$", "", filename)
        name, version, _build = filename.rsplit("-", 2)
        versions[name] = version
    return versions


def read_reference_versions():
    """Return {package name: version} from the Windows spec file"""
    return read_spec_versions(REFERENCE_SPEC)


def find_conda():
    conda = os.environ.get("CONDA_EXE") or shutil.which("conda")
    if not conda:
        sys.exit("conda not found")
    return conda


def solve(platform, specs, constraints):
    """Solve the environment for a platform and return the package URLs"""
    command = [
        find_conda(), "create", "--name", "_spec_file_solve", "--dry-run", "--json",
        "--platform", platform,
        "--override-channels", "--channel", "conda-forge",
        *specs,
    ]
    environment = dict(os.environ)
    environment["CONDA_PINNED_PACKAGES"] = "&".join(constraints)
    target_os = platform.split("-")[0]
    current_os = {"darwin": "osx", "win32": "win"}.get(sys.platform, sys.platform)
    if target_os != current_os:
        environment.update(VIRTUAL_PACKAGE_OVERRIDES.get(target_os, {}))
    result = subprocess.run(command, capture_output=True, text=True,
                            env=environment)
    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError:
        raise RuntimeError(result.stderr or result.stdout)
    if not data.get("success"):
        raise RuntimeError(data.get("message", result.stderr))
    urls = []
    for package in data["actions"]["LINK"]:
        url = f"{package['base_url']}/{package['platform']}/{package['dist_name']}"
        urls.append(add_extension(url))
    return urls


def add_extension(url):
    for extension in (".conda", ".tar.bz2"):
        request = urllib.request.Request(url + extension, method="HEAD")
        try:
            urllib.request.urlopen(request, timeout=30)
            return url + extension
        except urllib.error.HTTPError:
            pass
    raise RuntimeError(f"no package file found for {url}")


def write_spec_file(platform, urls):
    path = ROOT / f"spec-file-{platform}.txt"
    header = [
        "# This file may be used to create an environment using:",
        "# $ conda create --name <env> --file <this file>",
        f"# platform: {platform}",
        "# generated by generate_spec_files.py from spec-file-win-64.txt",
        "@EXPLICIT",
    ]
    path.write_text("\n".join(header + urls) + "\n")
    print(f"wrote {path.name} ({len(urls)} packages)")


def check_spec_file(platform, required, versions):
    path = ROOT / f"spec-file-{platform}.txt"
    if not path.exists():
        return [f"{path.name} does not exist"]
    lines = path.read_text().splitlines()
    problems = []
    if f"# platform: {platform}" not in lines:
        problems.append(f"{path.name} is missing '# platform: {platform}'")
    if "@EXPLICIT" not in lines:
        problems.append(f"{path.name} is missing '@EXPLICIT'")
    for line in lines:
        if line.startswith("http") and f"/{platform}/" not in line and "/noarch/" not in line:
            problems.append(f"{path.name} has a package for another platform: {line}")
    platform_versions = read_spec_versions(path)
    for name in required + EXTRA_PINNED:
        if name not in platform_versions:
            if name in required:
                problems.append(f"{path.name} is missing {name}")
        elif platform_versions[name] != versions[name]:
            problems.append(f"{path.name} has {name}={platform_versions[name]}, "
                            f"{REFERENCE_SPEC.name} has {versions[name]}")
    return problems


def check(platforms, required, versions):
    problems = []
    for platform in platforms:
        problems += check_spec_file(platform, required, versions)
    for problem in problems:
        print(problem)
    if problems:
        sys.exit("spec files are out of date, run: python generate_spec_files.py")
    print(f"spec files match {REFERENCE_SPEC.name}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate the macOS and Linux spec files from the Windows spec file.")
    parser.add_argument("platforms", nargs="*", metavar="platform",
                        help=f"one of {', '.join(PLATFORMS)} (default: all)")
    parser.add_argument("--check", action="store_true",
                        help="validate the existing spec files instead of generating them")
    args = parser.parse_args()
    for platform in args.platforms:
        if platform not in PLATFORMS:
            parser.error(f"unknown platform {platform}, choose from {', '.join(PLATFORMS)}")
    platforms = args.platforms or PLATFORMS
    versions = read_reference_versions()
    specs = []
    required = []
    for name in read_environment_packages():
        if name == "pip":
            specs.append(name)
        elif name in versions:
            specs.append(f"{name}={versions[name]}")
            required.append(name)
        else:
            sys.exit(f"{name} is in environment.yml but not in {REFERENCE_SPEC.name}")
    if args.check:
        check(platforms, required, versions)
        return
    constraints = [f"{name}={versions[name]}" for name in EXTRA_PINNED]
    print("required:", " ".join(specs))
    print("constrained:", " ".join(constraints))
    for platform in platforms:
        print(f"solving {platform}...", flush=True)
        write_spec_file(platform, solve(platform, specs, constraints))


if __name__ == "__main__":
    main()
